# project settings
NAME = ft_hexdump

# directories settings
SRC_DIR = src
OBJ_DIR = obj
INC_DIR = include

# files path settings
FILES = main.c
HEADER_FILES = ft_hexdump.h
SRCS = $(addprefix $(SRC_DIR)/, $(FILES))
OBJS = $(addprefix $(OBJ_DIR)/, $(FILES:%.c=%.o))
HEADERS = $(addprefix $(INC_DIR)/, $(HEADER_FILES))

# compiler settings

# commands

# targets